name: Push repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo (Repo A)
      uses: actions/checkout@v3

    - name: Clone destination repo (Repo B)
      run: |
        git config --global user.email "james.gbetchedji@epitech.eu"
        git config --global user.name "Noge"
        git clone https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/nogebeat/Arcade-Games.git repo-b
        rm -rf repo-b/*
        rsync -a --exclude='.git' ./ repo-b/

    - name: Commit and push to destination repo
      run: |
        cd repo-b
        git add .
        git commit -m "Sync full repo from Repo A" || echo "Nothing to commit"
        git push origin main
